### ISSUE TITLE
Possible to support socks5 proxy?

### ISSUE THREAD

**Issue by aj3423** [CUCyber/ja3transport#9]
I'm trying to connect through socks5 proxy, I found [another thread](https://github.com/CUCyber/ja3transport/issues/4) about how to use *https* proxy, I tried with socks5:

```golang
	ja3_transport, _ := ja3transport.NewTransportWithConfig(ja3_str, &utls.Config{
		InsecureSkipVerify: true,
	})

	// set proxy
	u, _ := url.Parse("socks5://....")
	ja3_transport.Proxy = http.ProxyURL(u)

	client := &http.Client{
		Transport: ja3_transport,
	}

	req, _ := http.NewRequest(method, "https://....", nil)

	client.Do(req)
```

- When the proxy is enabled by `ja3_transport.Proxy = http.ProxyURL(u)`, the proxy works but the ja3 config doesn't work, I captured the packets in Wireshark, it's not the value I set, it's the default value from Golang.
- If the proxy is removed, ja3 works fine

Is it possible to use both?

**Comment by t94j0** [comment]
Using a proxy will encapsulate the source TLS ClientHello and use the proxy's ClientHello, so your JA3 fingerprint will change if you're using a proxy at all. If you need to change the fingerprint, you'll need to change the fingerprint on the proxy, not the client.
